# Generated by Django 4.1.4 on 2022-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('documento', models.CharField(max_length=30, unique=True, verbose_name='Documento')),
                ('puntos', models.IntegerField(verbose_name='Puntos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
