# Generated by Django 4.1.4 on 2022-12-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('equipo_local', models.CharField(max_length=30, verbose_name='Equipo Local')),
                ('equipo_visitante', models.CharField(max_length=30, verbose_name='Equipo Visitante')),
                ('marcador_local', models.IntegerField(verbose_name='Marcador equipo local')),
                ('marcador_visitante', models.IntegerField(verbose_name='Marcador equipo visitante')),
                ('tarjetas_amarillas', models.IntegerField(verbose_name='Tarjetas amarillas')),
                ('tarjetas_rojas', models.IntegerField(verbose_name='Tarjetas rojas')),
                ('goles', models.IntegerField(verbose_name='Tiros de esquina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=30, verbose_name='Equipo Local')),
            ],
        ),
    ]
