# Generated by Django 4.1.4 on 2022-12-17 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidos',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partidos.resultado'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='goles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de goles'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='marcador_local',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marcador equipo local'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='marcador_visitante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Marcador equipo visitante'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='tarjetas_amarillas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarjetas amarillas'),
        ),
        migrations.AlterField(
            model_name='partidos',
            name='tarjetas_rojas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tarjetas rojas'),
        ),
    ]
