# Generated by Django 4.1.4 on 2022-12-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_partidos_resultado_alter_partidos_goles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='resultado',
            field=models.CharField(max_length=30, verbose_name='Resultado'),
        ),
    ]
