# Generated by Django 4.1.4 on 2022-12-17 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apuesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoapuesta',
            name='puntos',
            field=models.IntegerField(default=0, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='apuesta',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apuesta.estado'),
        ),
    ]
